services:

    calista.view.spout_xlsx_stream:
        public: true
        class: MakinaCorpus\Calista\View\ViewRenderer\SpoutXlsxStreamViewRenderer
        arguments: ['@calista.property_renderer']
        tags: [{name: calista.view, id: spout_xlsx_stream}]
